name: Deploy to Droplet
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            # Go to the http folder
            cd /var/www/http/
            
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            
            # Build the app
            npm run build
            pm2 restart all
